#step 1 data exploration and loading

In [ ]:
import pandas as pd
import pymysql
#mysql toolkit
import pymysql
from sqlalchemy import create_engine
#psql
import psycopg2
df=pd.read_csv("Walmart.csv",encoding_errors='ignore')
print(df.shape)

(10051, 11)

In [23]:
print(df.head())

   invoice_id   Branch         City                category unit_price  \
0           1  WALM003  San Antonio       Health and beauty     $74.69
1           2  WALM048    Harlingen  Electronic accessories     $15.28
2           3  WALM067  Haltom City      Home and lifestyle     $46.33
3           4  WALM064      Bedford       Health and beauty     $58.22
4           5  WALM013       Irving       Sports and travel     $86.31

   quantity      date      time payment_method  rating  profit_margin
0       7.0  05/01/19  13:08:00        Ewallet     9.1           0.48
1       5.0  08/03/19  10:29:00           Cash     9.6           0.48
2       7.0  03/03/19  13:23:00    Credit card     7.4           0.33
3       8.0  27/01/19  20:33:00        Ewallet     8.4           0.33
4       7.0  08/02/19  10:37:00        Ewallet     5.3           0.48

to get statistical data of dataset

In [24]:

print(df.describe())

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [25]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB
None

In [6]:
print(df.duplicated().sum())

51

In [26]:
df.drop_duplicates(inplace=True)
print(df.duplicated().sum())

0

In [27]:
df.shape

(10000, 11)

In [28]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

31 row is null in 2 column so we simply removing the all 31 row

In [29]:
df.dropna(inplace=True)

In [30]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [31]:
df.dtypes

invoice_id          int64
Branch                str
City                  str
category              str
unit_price            str
quantity          float64
date                  str
time                  str
payment_method        str
rating            float64
profit_margin     float64
dtype: object

second problem is unit pricw is in str but it should be int or float so to convert this, first we should remove or replace the $ symbol from unit

In [36]:
df['unit_price'].astype(float)

0       74.69
1       15.28
2       46.33
3       58.22
4       86.31
        ...
9995    37.00
9996    58.00
9997    52.00
9998    79.00
9999    62.00
Name: unit_price, Length: 9969, dtype: float64


df['unit_price'].str.replace('$','').astype(float)
df.head()

above shows that not implmented in actuall column so that what we do is we assigning again

In [37]:
df['unit_price']= df['unit_price'].astype(float)
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [34]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [38]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [39]:
df['total']=df['quantity']*df['unit_price']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17